[lint]
select = ["E", "F", "UP", "B", "SIM", "I"] # Rules can be looked up here https://docs.astral.sh/ruff/rules/
ignore = ["E501"]

[format]
quote-style = "double"
line-ending = "auto"
docstring-code-format = true


